config/routes.rb
Rails.application.routes.draw do

  get 'cart/show'
  devise_for :users
  root to: 'restaurants#index'
  resources :restaurants, only: [:index, :show]
  resources :orders, only: [:create]
  get '/order_success', to: 'pages#success'
  get '/cart', to: 'cart#show'
  post '/cartinfo', to: 'cart#cartinfo'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :dishes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
  end

  def cartinfo
    total = 0
    params.permit![:_json].map do |param|
      dish = Dish.find(param['dishId'])
      total += ( dish.price.to_i  * param['amount'].to_i )
      param.merge!( { dishPrice: dish.price,
                     dishName: dish.name
                    })
    end
      respond_to do |format|
        format.json { render json: { items: params[:_json], total: total } }
      end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    order = Order.new(details: order_details )
    order.user = current_user
    order.status = 'confirmed'
    order.save
    respond_to do |format|
      format.json { render json: { data: 'confirmed' } }
    end
  end

  private

  def order_details
    params.permit![:_json]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def success
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart/show.html.erb
<h4>This is your cart, <%= current_user.email %></h4>

<div id="cart">



</div>

   <button id="submit-order" class="d-none btn btn-primary"> Create Order</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantsWithCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="container mt-5"><%= yield %></div>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/success.html.erb
<h4> Hooray! </h4>

<p> Your order is on the way </p>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>

<% @restaurants.each do |restaurant| %>
    <%= link_to restaurant_path(restaurant), class: "text-decoration-none" do %>
    <div>
      <h4> <%= restaurant.name %>  </h4>
    </div>
    <% end %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>

<% @restaurant.dishes.each do |dish| %>
  <div class="card border shadow-sm p-3 mb-3">
    <div class="d-flex justify-content-between align-items-center w-50">
      <div class="dish-info">
        <h3> <%= dish.name %> </h3>
        <p> <%= dish.price %>  USD </p>
      </div>
      <button
        class="btn btn-primary"
        data-toggle="modal"
        data-target="#exampleModal"
        data-dish-name="<%= dish.name %>"
        data-dish-price="<%= dish.price %>"
        data-dish-id="<%= dish.id %>">
            add to cart
      </button>
    </div>
  </div>
<% end %>


<div class="modal fade"
      id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
      data-current-dish-id="any">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header flex-column">
        <h5 class="modal-title" id="exampleModalLabel">Order</h5>
        <p class="text-muted modal-price"> USD</p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="dish-name" class="col-form-label">Amount</label>
            <input type="number" class="form-control" id="dish-amount">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Special Request</label>
            <textarea class="form-control" id="special-instructions"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" data-dismiss="modal" class="btn btn-primary btn-modal">Add to Cart</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Cart", cart_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>